//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name itemName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeItemCount", ReplyAction="*")]
        TestApplication.ServiceReference1.ChangeItemCountResponse ChangeItemCount(TestApplication.ServiceReference1.ChangeItemCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeItemCount", ReplyAction="*")]
        System.Threading.Tasks.Task<TestApplication.ServiceReference1.ChangeItemCountResponse> ChangeItemCountAsync(TestApplication.ServiceReference1.ChangeItemCountRequest request);
        
        // CODEGEN: Generating message contract since element name GetItemListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemList", ReplyAction="*")]
        TestApplication.ServiceReference1.GetItemListResponse GetItemList(TestApplication.ServiceReference1.GetItemListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemList", ReplyAction="*")]
        System.Threading.Tasks.Task<TestApplication.ServiceReference1.GetItemListResponse> GetItemListAsync(TestApplication.ServiceReference1.GetItemListRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmailToNewsLetter", ReplyAction="*")]
        TestApplication.ServiceReference1.AddEmailToNewsLetterResponse AddEmailToNewsLetter(TestApplication.ServiceReference1.AddEmailToNewsLetterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEmailToNewsLetter", ReplyAction="*")]
        System.Threading.Tasks.Task<TestApplication.ServiceReference1.AddEmailToNewsLetterResponse> AddEmailToNewsLetterAsync(TestApplication.ServiceReference1.AddEmailToNewsLetterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeItemCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeItemCount", Namespace="http://tempuri.org/", Order=0)]
        public TestApplication.ServiceReference1.ChangeItemCountRequestBody Body;
        
        public ChangeItemCountRequest() {
        }
        
        public ChangeItemCountRequest(TestApplication.ServiceReference1.ChangeItemCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeItemCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string itemName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int count;
        
        public ChangeItemCountRequestBody() {
        }
        
        public ChangeItemCountRequestBody(string itemName, int count) {
            this.itemName = itemName;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeItemCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeItemCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestApplication.ServiceReference1.ChangeItemCountResponseBody Body;
        
        public ChangeItemCountResponse() {
        }
        
        public ChangeItemCountResponse(TestApplication.ServiceReference1.ChangeItemCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeItemCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangeItemCountResult;
        
        public ChangeItemCountResponseBody() {
        }
        
        public ChangeItemCountResponseBody(bool ChangeItemCountResult) {
            this.ChangeItemCountResult = ChangeItemCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemList", Namespace="http://tempuri.org/", Order=0)]
        public TestApplication.ServiceReference1.GetItemListRequestBody Body;
        
        public GetItemListRequest() {
        }
        
        public GetItemListRequest(TestApplication.ServiceReference1.GetItemListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetItemListRequestBody {
        
        public GetItemListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetItemListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetItemListResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestApplication.ServiceReference1.GetItemListResponseBody Body;
        
        public GetItemListResponse() {
        }
        
        public GetItemListResponse(TestApplication.ServiceReference1.GetItemListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetItemListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TestApplication.ServiceReference1.ArrayOfString GetItemListResult;
        
        public GetItemListResponseBody() {
        }
        
        public GetItemListResponseBody(TestApplication.ServiceReference1.ArrayOfString GetItemListResult) {
            this.GetItemListResult = GetItemListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmailToNewsLetterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmailToNewsLetter", Namespace="http://tempuri.org/", Order=0)]
        public TestApplication.ServiceReference1.AddEmailToNewsLetterRequestBody Body;
        
        public AddEmailToNewsLetterRequest() {
        }
        
        public AddEmailToNewsLetterRequest(TestApplication.ServiceReference1.AddEmailToNewsLetterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmailToNewsLetterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public AddEmailToNewsLetterRequestBody() {
        }
        
        public AddEmailToNewsLetterRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmailToNewsLetterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmailToNewsLetterResponse", Namespace="http://tempuri.org/", Order=0)]
        public TestApplication.ServiceReference1.AddEmailToNewsLetterResponseBody Body;
        
        public AddEmailToNewsLetterResponse() {
        }
        
        public AddEmailToNewsLetterResponse(TestApplication.ServiceReference1.AddEmailToNewsLetterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEmailToNewsLetterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEmailToNewsLetterResult;
        
        public AddEmailToNewsLetterResponseBody() {
        }
        
        public AddEmailToNewsLetterResponseBody(string AddEmailToNewsLetterResult) {
            this.AddEmailToNewsLetterResult = AddEmailToNewsLetterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : TestApplication.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<TestApplication.ServiceReference1.WebServiceSoap>, TestApplication.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestApplication.ServiceReference1.ChangeItemCountResponse TestApplication.ServiceReference1.WebServiceSoap.ChangeItemCount(TestApplication.ServiceReference1.ChangeItemCountRequest request) {
            return base.Channel.ChangeItemCount(request);
        }
        
        public bool ChangeItemCount(string itemName, int count) {
            TestApplication.ServiceReference1.ChangeItemCountRequest inValue = new TestApplication.ServiceReference1.ChangeItemCountRequest();
            inValue.Body = new TestApplication.ServiceReference1.ChangeItemCountRequestBody();
            inValue.Body.itemName = itemName;
            inValue.Body.count = count;
            TestApplication.ServiceReference1.ChangeItemCountResponse retVal = ((TestApplication.ServiceReference1.WebServiceSoap)(this)).ChangeItemCount(inValue);
            return retVal.Body.ChangeItemCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestApplication.ServiceReference1.ChangeItemCountResponse> TestApplication.ServiceReference1.WebServiceSoap.ChangeItemCountAsync(TestApplication.ServiceReference1.ChangeItemCountRequest request) {
            return base.Channel.ChangeItemCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestApplication.ServiceReference1.ChangeItemCountResponse> ChangeItemCountAsync(string itemName, int count) {
            TestApplication.ServiceReference1.ChangeItemCountRequest inValue = new TestApplication.ServiceReference1.ChangeItemCountRequest();
            inValue.Body = new TestApplication.ServiceReference1.ChangeItemCountRequestBody();
            inValue.Body.itemName = itemName;
            inValue.Body.count = count;
            return ((TestApplication.ServiceReference1.WebServiceSoap)(this)).ChangeItemCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestApplication.ServiceReference1.GetItemListResponse TestApplication.ServiceReference1.WebServiceSoap.GetItemList(TestApplication.ServiceReference1.GetItemListRequest request) {
            return base.Channel.GetItemList(request);
        }
        
        public TestApplication.ServiceReference1.ArrayOfString GetItemList() {
            TestApplication.ServiceReference1.GetItemListRequest inValue = new TestApplication.ServiceReference1.GetItemListRequest();
            inValue.Body = new TestApplication.ServiceReference1.GetItemListRequestBody();
            TestApplication.ServiceReference1.GetItemListResponse retVal = ((TestApplication.ServiceReference1.WebServiceSoap)(this)).GetItemList(inValue);
            return retVal.Body.GetItemListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestApplication.ServiceReference1.GetItemListResponse> TestApplication.ServiceReference1.WebServiceSoap.GetItemListAsync(TestApplication.ServiceReference1.GetItemListRequest request) {
            return base.Channel.GetItemListAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestApplication.ServiceReference1.GetItemListResponse> GetItemListAsync() {
            TestApplication.ServiceReference1.GetItemListRequest inValue = new TestApplication.ServiceReference1.GetItemListRequest();
            inValue.Body = new TestApplication.ServiceReference1.GetItemListRequestBody();
            return ((TestApplication.ServiceReference1.WebServiceSoap)(this)).GetItemListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestApplication.ServiceReference1.AddEmailToNewsLetterResponse TestApplication.ServiceReference1.WebServiceSoap.AddEmailToNewsLetter(TestApplication.ServiceReference1.AddEmailToNewsLetterRequest request) {
            return base.Channel.AddEmailToNewsLetter(request);
        }
        
        public string AddEmailToNewsLetter(string email) {
            TestApplication.ServiceReference1.AddEmailToNewsLetterRequest inValue = new TestApplication.ServiceReference1.AddEmailToNewsLetterRequest();
            inValue.Body = new TestApplication.ServiceReference1.AddEmailToNewsLetterRequestBody();
            inValue.Body.email = email;
            TestApplication.ServiceReference1.AddEmailToNewsLetterResponse retVal = ((TestApplication.ServiceReference1.WebServiceSoap)(this)).AddEmailToNewsLetter(inValue);
            return retVal.Body.AddEmailToNewsLetterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestApplication.ServiceReference1.AddEmailToNewsLetterResponse> TestApplication.ServiceReference1.WebServiceSoap.AddEmailToNewsLetterAsync(TestApplication.ServiceReference1.AddEmailToNewsLetterRequest request) {
            return base.Channel.AddEmailToNewsLetterAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestApplication.ServiceReference1.AddEmailToNewsLetterResponse> AddEmailToNewsLetterAsync(string email) {
            TestApplication.ServiceReference1.AddEmailToNewsLetterRequest inValue = new TestApplication.ServiceReference1.AddEmailToNewsLetterRequest();
            inValue.Body = new TestApplication.ServiceReference1.AddEmailToNewsLetterRequestBody();
            inValue.Body.email = email;
            return ((TestApplication.ServiceReference1.WebServiceSoap)(this)).AddEmailToNewsLetterAsync(inValue);
        }
    }
}
